version: '3.8'

services:
  db:
    image: docker.io/postgres:13.2
    container_name: cod-wz-tournament-database
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "cod-wz-tournament"
      POSTGRES_PASSWORD: "cod-wz-tournament"
      POSTGRES_DB: "cod-wz-tournament"
    networks:
      - "cod-wz-tournament-api"

  api:
    image: docker.io/ttirtia/cod-wz-tournament-api:latest
    container_name: cod-wz-tournament-api
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      NODE_ENV: "dev"
      PGUSER: "cod-wz-tournament"
      PGPASSWORD: "cod-wz-tournament"
      PGDATABASE: "cod-wz-tournament"
      PGHOST: "db"
      JWT_SIGNING_KEY: "supersecret"
    networks:
      - "cod-wz-tournament-api"

  web:
    build: .
    container_name: cod-wz-tournament-web
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      NODE_ENV: "production"
      VUE_APP_HOST_URL: "http://localhost:8080"
      VUE_APP_GRAPHQL_HTTP: "http://localhost:8888/graphql"

networks:
  cod-wz-tournament-api:
